baseurl = "https://example.org/"
title = "Creative portfolio"
theme = "creative"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "green"
  description = "Describe your website"
  copyright = "2018"
  sidebarAbout = [
    "Software engineer, developer and crafstman. Focused on building software that helps people, and helping people build software.",
    "Puebla, MX"
  ]


  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "portfolio/"
  home = true

  [params.social]
  # facebook      = "full page or profile url in facebook"
  # googleplus    = "full profile url in googleplus"
  # email         = "email@example.com"
  # twitter       = "full profile url in twitter"
  # linkedin      = "full profile url in linkedin"
  # stackoverflow = "full profile url in stackoverflow"
  # instagram     = "full profile url in instagram"
  github        = "https://github.com/bul-ikana"
